language: php

php:
 - 5.5
 - 5.4

install:
  - which composer
  - cat `which composer`
  - composer require --prefer-dist --dev 'codeception/codeception *' 'codeception/specify *'

script:
  - echo "done."
