language: php

php:
 - 5.5
 - 5.4

install:
  - echo "*"
  - echo '*'
  - echo *
  - echo "\*"
  - echo '\*'
  - echo \*
  - echo "test *"
  - echo 'test *'
  - echo test *
  - echo "codeception/codeception *"
  - echo 'codeception/codeception *'
  - echo codeception/codeception *

script:
  - echo "done."
